language: node_js
node_js:
  - "10"

env:
  - NODE_ENV=test
  global:
   - COVERALLS_REPO_TOKEN=2dT2jYOgAO5u8sGRQAvdnhuqVSoC678Lq

services: mongodb

script: 
  - npm run test

after_success:
  - npm run coverage
