language: node_js
node_js:
  - "10"

dist: trusty

sudo: required

before_install:
  - export CHROME_BIN=chrome-browser
  - export display=:99.0
  - sh -e /etc/init.d/xvfb start
  
addons:
  chrome: stable

env:
  - NODE_ENV=test

services: mongodb

cache:
  directories:
    - 'node_modules'

script:
  - npm run test

after_success:
  - npm run coverage

after_failure:
  - npm run coverage
